// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhmxOB2VAXpaEUOAmmkuS7PXaY16UCR8g',
    appId: '1:749866432875:web:3ec2c7d0c152297da6b42e',
    messagingSenderId: '749866432875',
    projectId: 'miuco-84e63',
    authDomain: 'miuco-84e63.firebaseapp.com',
    storageBucket: 'miuco-84e63.appspot.com',
    measurementId: 'G-L4W1DCKWS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAajgHYfInxnQ2ZnvycLezN2l9rn_PMXFg',
    appId: '1:749866432875:android:b2f7339a80b7b05fa6b42e',
    messagingSenderId: '749866432875',
    projectId: 'miuco-84e63',
    storageBucket: 'miuco-84e63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFJIRzhA4J6-O8DDKcGfm-C5K-8sxZsgQ',
    appId: '1:749866432875:ios:228ac4c2289b5076a6b42e',
    messagingSenderId: '749866432875',
    projectId: 'miuco-84e63',
    storageBucket: 'miuco-84e63.appspot.com',
    iosClientId: '749866432875-b960no3r7spmsor9jgi3n2rmgovk8368.apps.googleusercontent.com',
    iosBundleId: 'com.example.miuco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFJIRzhA4J6-O8DDKcGfm-C5K-8sxZsgQ',
    appId: '1:749866432875:ios:228ac4c2289b5076a6b42e',
    messagingSenderId: '749866432875',
    projectId: 'miuco-84e63',
    storageBucket: 'miuco-84e63.appspot.com',
    iosClientId: '749866432875-b960no3r7spmsor9jgi3n2rmgovk8368.apps.googleusercontent.com',
    iosBundleId: 'com.example.miuco',
  );
}
